if ($PSVersionTable.PSVersion.Major -gt 5) {
    # GetDeviceProperties is only available if running in Powershell 5.1.
    powershell.exe -noprofile -file $MyInvocation.MyCommand.Path
    exit
}

try {
    $OldWindow = $null

    foreach ($Port in ([System.IO.Ports.SerialPort]::GetPortNames())) {
        $Desc = (Get-WmiObject Win32_PnPEntity | Where-Object Name -match "$Port").GetDeviceProperties('DEVPKEY_Device_BusReportedDeviceDesc').deviceProperties.Data
        # CDC2 is the usb_cdc.data serial port
        if ($Desc -match 'CDC2') {
            $ComPort = $Port
        }
    }

    if (!$ComPort) {
        Write-Error 'Could not find MacroPad attached to system.'
        exit
    }

    Write-Host 'Found MacroPad on port ' -NoNewline
    Write-Host $ComPort -ForegroundColor Green

    $Port = [System.IO.Ports.SerialPort]::new($ComPort, 115200)
    # Enable DTR, otherwise Macropad will not detect that it is connected, even though it will receive data.
    # Absolutely necessary on versions 8.0.0-beta.4 and later as a fix was put in that makes it necessary to be
    # connected before allowing a read.
    $Port.DtrEnable = $true
    $Port.Open()

    # Load DLL to retrieve process name. This is used because there is no good way to handle UWP processes
    #       like Calculator or Windows store otherwise.

    # This is how $blob is created.
    # $FilePath = "<Path to ProcessIO.dll>"
    # $File = [System.IO.File]::ReadAllBytes($FilePath)
    # $blob = [System.Convert]::ToBase64String($File)

    $blob = 'TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAATAEDAPn7EqkAAAAAAAAAAOAAIiALATAAABAAAAAGAAAAAAAANi8AAAAgAAAAQAAAAAAAEAAgAAAAAgAABAAAAAAAAAAGAAAAAAAAAACAAAAAAgAAAAAAAAMAYIUAABAAABAAAAAAEAAAEAAAAAAAABAAAAAAAAAAAAAAAOQuAABPAAAAAEAAAHgDAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAwAAAA4LgAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAACCAAAEgAAAAAAAAAAAAAAC50ZXh0AAAAPA8AAAAgAAAAEAAAAAIAAAAAAAAAAAAAAAAAACAAAGAucnNyYwAAAHgDAAAAQAAAAAQAAAASAAAAAAAAAAAAAAAAAABAAABALnJlbG9jAAAMAAAAAGAAAAACAAAAFgAAAAAAAAAAAAAAAAAAQAAAQgAAAAAAAAAAAAAAAAAAAAAYLwAAAAAAAEgAAAACAAUACCIAADAMAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMwBACiAAAAAQAAESgBAAAGCgZ+DwAACigQAAAKLAIUKgYSASgCAAAGJiAQBAAAFgcoBgAABiUMfg8AAAooEAAACiwSBygRAAAKJS0DJhQqKBIAAAoqINAHAAANCXMTAAAKEwQIFhEEEgMoBQAABiYRBBYJbxQAAAoTBREFKBUAAApyAQAAcG8WAAAKLAkGBygIAAAGEwURBSgVAAAKcjMAAHByPQAAcG8XAAAKKgAAEzAEAKkAAAACAAAREgb+FQIAAAISBgN9AQAABBIGA30CAAAEEQYKBigBAAArKBkAAAoLBgcWKAIAACsU/gYJAAAGcwsAAAYMAggHKAQAAAYmB9ACAAACKBsAAAooHAAACqUCAAACCiAQBAAAFgZ7AgAABCgGAAAGJQ1+DwAACigQAAAKLAIUKiDQBwAAEwQRBHMTAAAKEwUJFhEFEgQoBQAABiYHKB0AAAoRBRYRBG8UAAAKKgAAABMwAwA6AAAAAwAAEQPQAgAAAigbAAAKKBwAAAqlAgAAAgoCEgEoAgAABiYHBnsBAAAELggSAAd9AgAABAYDFygCAAArFyoeAigeAAAKKgAAQlNKQgEAAQAAAAAADAAAAHY0LjAuMzAzMTkAAAAABQBsAAAAcAQAACN+AADcBAAAKAUAACNTdHJpbmdzAAAAAAQKAABAAAAAI1VTAEQKAAAQAAAAI0dVSUQAAABUCgAA3AEAACNCbG9iAAAAAAAAAAIAAAFXPQIUCQoAAAD6ATMAFgAAAQAAABwAAAAEAAAABAAAAA4AAAAcAAAAHgAAAAIAAAAOAAAAAgAAAAMAAAADAAAABgAAAAEAAAACAAAAAQAAAAIAAAAAALgDAQAAAAAABgCMAlEEBgD5AlEEBgDAAR8EDwBxBAAABgDoAdQDBgBvAtQDBgBQAtQDBgDgAtQDBgCsAtQDBgDFAtQDBgD/AdQDBgDUATIEBgCyATIEBgAzAtQDBgAaAicDBgCHAc0DBgDOBM0DBgDrA/sEBgCgAc0DBgDcBM0DBgBPA80DBgAYBM0DCgC1BB8EBgBKA1QABgBDA80DBgCYAzIEBgCMAc0DBgDzAM0DAAAAAAgAAAAAAAEAAQAIARAASQAlAEEAAQABAAEAEACPBCUARQADAAEAAgEAAHIAAABNAAUACwAGAMAAowAGALcAowBWgC8AowBWgBEAowAAAAAAgACWIAcFpgABAAAAAACAAJYggQCqAAEAAAAAAIAAliCBALEAAwAAAAAAgACWIL0EtwAFAAAAAACAAJYgJgG/AAkAAAAAAIAAliCxBMkADQBQIAAAAACWAHIB0AAQAAAhAAAAAJEAVgHUABAAuCEAAAAAkQBdAycAEgD+IQAAAACGGAMEBgAUAAAAAAADAIYYAwTaABQAAAAAAAMAxgHsAOAAFgAAAAAAAwDGAecA5gAYAAAAAAADAMYB3QDwABwAAAABAMkAAgACAJoAAAABAMkAAAACAJ4AACAAAAAAAAABAPAEAAACAGcAAAADAMYDAQABAKgEAQACAIAEAgADAEwBAAAEABcDAAABAJgEACACABcBAAADAJwAAAABAMkAAAACACEAAAABAMkAAAACAMYDAAABANUEAAACAM4AAAABAMkAAAACAPkDAAABAMkAAAACAPkDAAADAHYDAAAEANUEAAABAOkECQADBAEAEQADBAYAGQADBAoAKQADBBAAMQADBBAAOQADBBAAQQADBBAASQADBBAAUQADBBAAWQADBBAAYQADBBUAaQADBBAAcQADBBAAeQADBBAAsQDmAyQAsQAbBScAuQCoAC0AuQBiATMAkQADBAEAkQBBAzcAwQBAAT0AyQCIBEIAyQDVAEcA0QAgA1sA0QB/A2cA0QAJBGwA2QAFAXUA0QCRAXwA0QCMA4MAiQADBAYACQAMAJcACQAQAJwALgALAPYALgATAP8ALgAbAB4BLgAjACcBLgArADYBLgAzADYBLgA7ADYBLgBDACcBLgBLADwBLgBTADYBLgBbADYBLgBjAFQBLgBrAH4BLgBzAIsBCwChAB0AoQAaAE0AiACtAwEAoAMAAQMABwUBAEABBQCBAAEAQAEHAIEAAQBAAQkAvQQCAEABCwAmAQMAQAENALEEAwAEgAAAAQAAAAAAAAAAAAAAAAAlAAAABAAAAAAAAAAAAAAAjgBeAAAAAAAEAAAAAAAAAAAAAACOAM0DAAAAAAQAAwAxAGIANQBiAAAAAAAAdXNlcjMyADxNb2R1bGU+AFBST0NFU1NfVk1fUkVBRABwSUQAUHJvY2Vzc0lEAFBST0NFU1NfUVVFUllfSU5GT1JNQVRJT04AV0lORE9XSU5GTwBTeXN0ZW0uSU8AbXNjb3JsaWIAbHBFbnVtRnVuYwBFbnVtV2luZG93UHJvYwBHZXRXaW5kb3dUaHJlYWRQcm9jZXNzSWQAbHBkd1Byb2Nlc3NJZABHZXRQcm9jZXNzQnlJZABjaGlsZHBpZABvd25lcnBpZABoV25kAG1ldGhvZABSZXBsYWNlAEVuZEludm9rZQBCZWdpbkludm9rZQBSdW50aW1lVHlwZUhhbmRsZQBHZXRUeXBlRnJvbUhhbmRsZQBiSW5oZXJpdEhhbmRsZQBRdWVyeUZ1bGxQcm9jZXNzSW1hZ2VOYW1lAEdldEZpbGVOYW1lAGxwRXhlTmFtZQBVV1BfQXBwTmFtZQBnZXRfUHJvY2Vzc05hbWUAR2V0QWN0aXZlUHJvY2Vzc05hbWUAVmFsdWVUeXBlAFB0clRvU3RydWN0dXJlAE11bHRpY2FzdERlbGVnYXRlAEd1aWRBdHRyaWJ1dGUARGVidWdnYWJsZUF0dHJpYnV0ZQBDb21WaXNpYmxlQXR0cmlidXRlAEFzc2VtYmx5VGl0bGVBdHRyaWJ1dGUAQXNzZW1ibHlUcmFkZW1hcmtBdHRyaWJ1dGUAVGFyZ2V0RnJhbWV3b3JrQXR0cmlidXRlAEFzc2VtYmx5RmlsZVZlcnNpb25BdHRyaWJ1dGUAQXNzZW1ibHlDb25maWd1cmF0aW9uQXR0cmlidXRlAEFzc2VtYmx5RGVzY3JpcHRpb25BdHRyaWJ1dGUAQ29tcGlsYXRpb25SZWxheGF0aW9uc0F0dHJpYnV0ZQBBc3NlbWJseVByb2R1Y3RBdHRyaWJ1dGUAQXNzZW1ibHlDb3B5cmlnaHRBdHRyaWJ1dGUAQXNzZW1ibHlDb21wYW55QXR0cmlidXRlAFJ1bnRpbWVDb21wYXRpYmlsaXR5QXR0cmlidXRlAGxwZHdTaXplAFNpemVPZgBTeXN0ZW0uUnVudGltZS5WZXJzaW9uaW5nAFRvU3RyaW5nAFBhdGgAQXN5bmNDYWxsYmFjawBFbnVtQ2hpbGRXaW5kb3dzQ2FsbGJhY2sAY2FsbGJhY2sAQWxsb2NIR2xvYmFsAEZyZWVIR2xvYmFsAE1hcnNoYWwAa2VybmVsMzIuZGxsAHVzZXIzMi5kbGwAUHJvY2Vzc0lELmRsbABsUGFyYW0AU3lzdGVtAFN5c3RlbS5SZWZsZWN0aW9uAFplcm8AU3RyaW5nQnVpbGRlcgBwYXJhbWV0ZXIALmN0b3IAU3RydWN0dXJlVG9QdHIASW50UHRyAFN5c3RlbS5EaWFnbm9zdGljcwBTeXN0ZW0uUnVudGltZS5JbnRlcm9wU2VydmljZXMAU3lzdGVtLlJ1bnRpbWUuQ29tcGlsZXJTZXJ2aWNlcwBEZWJ1Z2dpbmdNb2RlcwBkd0ZsYWdzAEVxdWFscwBVd3BVdGlscwBkd0Rlc2lyZWRBY2Nlc3MAaFByb2Nlc3MAT3BlblByb2Nlc3MARW51bUNoaWxkV2luZG93cwBPYmplY3QAb2JqZWN0AElBc3luY1Jlc3VsdAByZXN1bHQAaFduZFBhcmVudABTeXN0ZW0uVGV4dABHZXRGb3JlZ3JvdW5kV2luZG93AG9wX0VxdWFsaXR5AAAAMUEAcABwAGwAaQBjAGEAdABpAG8AbgBGAHIAYQBtAGUASABvAHMAdAAuAGUAeABlAAAJLgBlAHgAZQAAAQAA4Ie3iQ/PrU28eh9ufdrCrwAEIAEBCAMgAAEFIAEBEREEIAEBDgQgAQECCQcGGAkYCBJJDgIGGAUAAgIYGAUAARJdCAMgAA4FIAIOCAgEAAEODgQgAQIOBSACDg4ODQcHEQgYEhAYCBJJEQgGEAEBCB4ABAoBEQgEAAEYCAgQAQMBHgAYAgYAARJtEXEGAAIcGBJtBAABARgFBwIRCAkIt3pcVhk04IkEAAQAAAQQAAAAAQICBgkDAAAYBgACCRgQCQUAAhgYGAcAAwIYEhAYCQAEAhgIEkkQCAYAAxgJAggDAAAOBQACDhgJBSACARwYBSACAhgYCSAEElEYGBJVHAUgAQISUQgBAAgAAAAAAB4BAAEAVAIWV3JhcE5vbkV4Y2VwdGlvblRocm93cwEIAQACAAAAAAAOAQAJUHJvY2Vzc0lEAAAFAQAAAAAXAQASQ29weXJpZ2h0IMKpICAyMDIzAAApAQAkZGEwYzhmM2ItOTAzMS00NWYyLTliNjUtZDk0MWU3MTQ2MGZmAAAMAQAHMS4wLjAuMAAATQEAHC5ORVRGcmFtZXdvcmssVmVyc2lvbj12NC43LjIBAFQOFEZyYW1ld29ya0Rpc3BsYXlOYW1lFC5ORVQgRnJhbWV3b3JrIDQuNy4yAAAAAAAAAPBBg74AAAAAAgAAAHQAAABwLgAAcBAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAABSU0RTManAefr+mE+M/Q3RMYgxywEAAABEOlxVc2Vyc1xqb25cTmV4dGNsb3VkXCFTeXN0ZW0gRm9sZGVyc1xEb2N1bWVudHNcU291cmNlXFByb2Nlc3NJRFxvYmpcUmVsZWFzZVxQcm9jZXNzSUQucGRiAAwvAAAAAAAAAAAAACYvAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYLwAAAAAAAAAAAAAAAF9Db3JEbGxNYWluAG1zY29yZWUuZGxsAAAAAAD/JQAgABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABABAAAAAYAACAAAAAAAAAAAAAAAAAAAABAAEAAAAwAACAAAAAAAAAAAAAAAAAAAABAAAAAABIAAAAWEAAABwDAAAAAAAAAAAAABwDNAAAAFYAUwBfAFYARQBSAFMASQBPAE4AXwBJAE4ARgBPAAAAAAC9BO/+AAABAAAAAQAAAAAAAAABAAAAAAA/AAAAAAAAAAQAAAACAAAAAAAAAAAAAAAAAAAARAAAAAEAVgBhAHIARgBpAGwAZQBJAG4AZgBvAAAAAAAkAAQAAABUAHIAYQBuAHMAbABhAHQAaQBvAG4AAAAAAAAAsAR8AgAAAQBTAHQAcgBpAG4AZwBGAGkAbABlAEkAbgBmAG8AAABYAgAAAQAwADAAMAAwADAANABiADAAAAAaAAEAAQBDAG8AbQBtAGUAbgB0AHMAAAAAAAAAIgABAAEAQwBvAG0AcABhAG4AeQBOAGEAbQBlAAAAAAAAAAAAPAAKAAEARgBpAGwAZQBEAGUAcwBjAHIAaQBwAHQAaQBvAG4AAAAAAFAAcgBvAGMAZQBzAHMASQBEAAAAMAAIAAEARgBpAGwAZQBWAGUAcgBzAGkAbwBuAAAAAAAxAC4AMAAuADAALgAwAAAAPAAOAAEASQBuAHQAZQByAG4AYQBsAE4AYQBtAGUAAABQAHIAbwBjAGUAcwBzAEkARAAuAGQAbABsAAAASAASAAEATABlAGcAYQBsAEMAbwBwAHkAcgBpAGcAaAB0AAAAQwBvAHAAeQByAGkAZwBoAHQAIACpACAAIAAyADAAMgAzAAAAKgABAAEATABlAGcAYQBsAFQAcgBhAGQAZQBtAGEAcgBrAHMAAAAAAAAAAABEAA4AAQBPAHIAaQBnAGkAbgBhAGwARgBpAGwAZQBuAGEAbQBlAAAAUAByAG8AYwBlAHMAcwBJAEQALgBkAGwAbAAAADQACgABAFAAcgBvAGQAdQBjAHQATgBhAG0AZQAAAAAAUAByAG8AYwBlAHMAcwBJAEQAAAA0AAgAAQBQAHIAbwBkAHUAYwB0AFYAZQByAHMAaQBvAG4AAAAxAC4AMAAuADAALgAwAAAAOAAIAAEAQQBzAHMAZQBtAGIAbAB5ACAAVgBlAHIAcwBpAG8AbgAAADEALgAwAC4AMAAuADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAMAAAAOD8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    [void][System.Reflection.Assembly]::Load([Convert]::FromBase64String($blob))

    while ($true) {
        try {
            while (!$Port.IsOpen) {
                for ($i = 5; $i -gt 0; $i--) {
                    Write-Host "Port disconnected. Retry in $i seconds.`r" -NoNewline
                    Start-Sleep 1
                }
                $Port.Open()
                if ($Port.IsOpen) {
                    Write-Host "                                       `r" -NoNewline
                }
            }
        }
        catch {
            continue
        }

        $Window = [ProcessID.UwpUtils]::GetActiveProcessName()

        if ($Window -ne $OldWindow) {
            try {
                $Port.WriteLine(('{0}' -f $Window))
                $Port.ReadLine()
            }
            catch {
                continue
            }

            $OldWindow = $Window
        }
        Start-Sleep 1
    }
}
catch {
    Write-Error "Exception occurred: $_"
}
finally {
    Write-Host 'Closing Serial port'
    $Port.Close()
    $Port.Dispose()
    $Port = $null
}
